name: Create Cli Release

on:
  push:
    tags:
      - 'cli-v*'

permissions:
  id-token: write  # Required for OIDC trusted publishing
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'doocs/md'
    steps:
      - uses: actions/checkout@v7

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v7
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Update npm
        run: npm install -g npm@latest

      - run: bun install --frozen-lockfile
      - run: bun run build:cli

      - run: cd packages/md-cli && npm publish --registry=https://registry.npmjs.org/
